feat: WIL4_ssso.md
danbom/Zerobase-Study pull request #12
Opened 2022-07-16 11:10 UTC by ssso-pro1

2022-07-20 01:20 UTC, danbom requested changes
아직 전 리다이렉트(`3`으로 시작하는) 상태 코드들이 이해가 잘 가지 않아유............. 좀 더 공부해봐야겠네요ㅠ 이번 주도 수고하셨습니다!!!

2022-07-20 01:20 UTC, danbom commented on 그림으로 배우는 HTTP & Network Basic/결과를 전달하는 HTTP 상태 코드/WIL4_ssso.md
> +- 302와 같은 의미를 지니지만, 302는 POST로부터 GET치환이 금지되어 있는데도 불구하고 구현상 그와 같이 되어 있지 않는다. 뭔소리?
뭔소리? ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
`302` 상태 코드는 `POST` 요청을 `GET` 요청으로 치환하는 것을 형식적으로 금지해놨는데 실제로는 `GET` 요청으로 치환해 사용한다는 의미인 것 같아요 ㅋㅋㅋㅋㅋ

2022-07-20 02:46 UTC, ssso-pro1 commented on 그림으로 배우는 HTTP & Network Basic/결과를 전달하는 HTTP 상태 코드/WIL4_ssso.md
> +- 302와 같은 의미를 지니지만, 302는 POST로부터 GET치환이 금지되어 있는데도 불구하고 구현상 그와 같이 되어 있지 않는다. 뭔소리?
> 

저도 300 상태 코드들이 이해가 잘 안되더라구요,, 번역체라 더 그런 것 같아요.. 고생하셨습니다~!

2022-08-03 23:57 UTC, danbom approved these changes

2022-08-04 00:09 UTC, danbom reviewed
중간중간에 추가적인 정보들까지 적어주셔서 더 읽기 좋았습니당 수고하셨어요!! 👍

2022-08-04 00:09 UTC, danbom commented on 그림으로 배우는 HTTP & Network Basic/HTTP와 연계하는 웹 서버/WIL5_ssso.md
> +- 클라이언트 ← Request (프록시) → 서버 → Response (프록시) → 클라이언트
오타 수정
``` diff
- ←
+ →
```

2022-08-04 00:09 UTC, danbom commented on 그림으로 배우는 HTTP & Network Basic/HTTP와 연계하는 웹 서버/WIL5_ssso.md
> +- 클라이언트 ← Request (프록시) → 서버 → Response (프록시) → 클라이언트
`클라이언트` -(리퀘스트)→ `프록시` -(리퀘스트)→ `서버` -(리스폰스)→ `프록시` -(리스폰스)→ `클라이언트`
요 의미 맞죵!?

2022-08-04 00:09 UTC, danbom commented on 그림으로 배우는 HTTP & Network Basic/HTTP와 연계하는 웹 서버/WIL5_ssso.md
> +- 프록시 서버를 여러 대 경유하는 경우 여러 대 경유해서 중계하며, 이 때 `Via` 헤더 필드에 경유한 호스트 정보 추가 필요
프록시의 호스트 정보가 추가되는 건가요?? 이 부분 꼼꼼하게 공부를 안해서 정확히 모르겠네요😥

2022-08-04 00:11 UTC, ssso-pro1 commented on 그림으로 배우는 HTTP & Network Basic/HTTP와 연계하는 웹 서버/WIL5_ssso.md
> +- 클라이언트 ← Request (프록시) → 서버 → Response (프록시) → 클라이언트
오우 맞아요 감사합니다 :)

2022-08-04 06:14 UTC, merged